name: foodstar
description: food application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  #firebase_messaging: 6.0.16
  firebase_messaging: ^7.0.3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  #path_provider: ^1.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12
  fluttertoast: ^7.1.1
  http: ^0.12.2
  provider: ^4.3.2+2
  google_sign_in: ^4.5.4
  google_maps_flutter: ^1.0.3
  #google_maps_flutter: ^0.5.24+1
  #geolocator: 4.0.3
  #geolocator: ^5.3.2+2
  geolocator: ^6.0.0+4
  #location_permissions: ^2.0.1
  shimmer: ^1.1.2
  #url_launcher: 5.4.10
  steps_indicator: ^1.1.0
  connectivity: ^0.4.9+3
  data_connection_checker: ^0.3.4
  device_info: ^0.4.2+8
  package_info: ^0.4.3
  progress_dialog: ^1.2.4
  sqflite: ^1.3.1+1
  path_provider: ^1.6.18
  path: ^1.7.0
  device_preview: ^0.4.8
  #permission_handler: 5.0.1+1
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+11
  cached_network_image: ^2.3.2+1
  page_view_indicators: ^1.4.0
  share: ^0.6.5+2
  razorpay_flutter: ^1.2.2
  #flutter_google_places: 0.2.6
  google_maps_webservice: ^0.0.18
  geocoder: ^0.2.1
  webview_flutter: ^1.0.1
  #location: 3.0.2
  app_settings: ^4.0.4
  scroll_to_index: ^1.0.6
  socket_io_client: ^0.9.11
  geocoding: ^1.0.4+1
  url_launcher: ^5.7.2
  #google_map_polyline:
  android_intent: ^0.3.7+4
  scrollable_positioned_list: ^0.1.8
  overlay_support: ^1.0.5
  flutter_rating_bar: ^3.0.1+1
  location: ^3.0.2

dev_dependencies:
  intl_translation: ^0.17.10+1
  flutter_launcher_icons: ^0.8.0
  hive_generator: ^0.7.3
  build_runner: ^1.10.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
  #
  #    - family: Poppins
  #      fonts:
  #        - asset: fonts/Poppins/Poppins-Bold.ttf
  #        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
  #        - asset: fonts/Poppins/Poppins-Light.ttf
  #        - asset: fonts/Poppins/Poppins-Regular.ttf
  #        - asset: fonts/Poppins/Poppins-SemiBold.ttf


  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en
